# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'dummy-git-dependency', '1.0.0'

source "https://rubygems.pkg.github.com/mercell" do
  gem "sd-rails-utils", "0.1.0"
end